export const ADD_COMPUTER_FORM_VALUES = {
	pcType: "",
	pcName: "",
	pcPurpose: "",
	formFactor: "",
	motherboard: "",
	numOfSockets: "",
	typeOfSocket: "",
	maxRamSize: "",
	sataType: "",
	numOfSataPorts: "",
	raid: "",
	numOfPsu: "",
	psuPower: "",
	os: "",
	numOfCpu: "",
	cpuModel: "",
	numOfCores: "",
	cpuFrequency: "",
	cpuL1Cache: "",
	cpuL2Cache: "",
	cpuL3Cache: "",
	ramType: "",
	ramTotalModules: "",
};
